From ubuntu:20.04

Run apt-get update && apt-get install -y sudo
Run sudo apt-get install -y vim
Run sudo apt-get install -y git
Run sudo apt-get install -y openjdk-11-jdk
Run sudo apt install -y maven

Run mkdir root/project
WORKDIR root/project
ADD run.sh .

